<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>8</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);TestProject\**</DefaultItemExcludes>
  </PropertyGroup>


  <ItemGroup>
    <Content Include="Images\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Objects\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Maps\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Sounds\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>

